import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UIProvider, colorModeManager, ColorModeScript } from '@yamada-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <ColorModeScript type="cookie" nonce="testing" />

                <UIProvider colorModeManager={{ ...colorModeManager }.cookieStorage}>{children}</UIProvider>
            </body>
        </html>
    )
}
